### ISSUE TITLE
No saved model found

### ISSUE THREAD

**Issue by raina99** [githubharald/SimpleHTR#1]
Python: 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
Tensorflow: 1.8.0
2018-06-25 17:43:33.775081: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Traceback (most recent call last):
  File "main.py", line 97, in <module>
    infer(fnInfer)
  File "main.py", line 86, in infer
    model = Model(open(fnCharList).read(), mustRestore=True)
  File "/home/jatinpal/goall/SimpleHTR/src/Model.py", line 33, in __init__
    (self.sess, self.saver) = self.setupTF()
  File "/home/jatinpal/goall/SimpleHTR/src/Model.py", line 106, in setupTF
    raise Exception('No saved model found in: ' + modelDir)
Exception: No saved model found in: ../model/

can anyone suggest why I an not able to locate the saved model .
My laptop details
ubuntu 16.04,8GB  RAM, 
python 3.6.3(anaconda)
tensorflow 1.8.0
cv2 3.4.1

**Comment by githubharald** [comment]
Did you unzip the file model.zip, located in the model directory?

**Comment by raina99** [comment]
yes I did unzip in the same  directory  and new folder model created present along with accuracy.txt and charLists.txt files
 so the path  along with files is as
 goall being my folder 
~/goall/SimpleHTR/model/model$ ls
checkpoint                       snapshot-13.index
snapshot-13.data-00000-of-00001  snapshot-13.meta

**Comment by githubharald** [comment]
Snapshot files should be in model dir, i.e. same dir as accuracy.txt. Copy content of model/model one level up.

**Comment by raina99** [comment]
Yes it works but its gives another error 

Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Init with stored values from ../model/snapshot-13

2018-06-25 21:03:34.839475: W tensorflow/core/framework/allocator.cc:101] Allocation of 26214400 exceeds 10% of system memory.
2018-06-25 21:03:34.896287: W tensorflow/core/framework/allocator.cc:101] Allocation of 13107200 exceeds 10% of system memory.
Recognized: "little"

I have almost same memory specifications as yours but still its showing memory constrains

**Comment by githubharald** [comment]
These are warnings from TF (which I don't get with my system). I think you can safely ignore them. If you want more information about these warnings, please create an issue in the TF repo.

Regards 
Harry

**Comment by anumitgarg** [comment]
This model doesn't work for digits. Can anyone suggest a quickfix to make it compatible with digits also.
