### ISSUE TITLE
Probelm in Trasnfert Learning from IAM weights

### ISSUE THREAD

**Issue by Sofiane23i** [githubharald/SimpleHTR#101]
Hello, 

Thank you very much for this code, it works very well.

However, i prepared a new dataset composed of 1775 images, when i try to train from IAM weights i got erros, any interpretation please.

```
OP_REQUIRES failed at conv_grad_filter_ops.cc:447 : Invalid argument: Conv2DCustomBackpropFilter: filter and out_backprop must have the same out_depth
Traceback (most recent call last):
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilter: filter and out_backprop must have the same out_depth
	 [[{{node gradients/convolution_grad/Conv2DBackpropFilter}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 158, in <module>
    main()
  File "main.py", line 146, in main
    train(model, loader)
  File "main.py", line 44, in train
    loss = model.trainBatch(batch)
  File "/home/useradmin/SimpleHTR/src/Model.py", line 218, in trainBatch
    _, lossVal = self.sess.run(evalList, feedDict)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilter: filter and out_backprop must have the same out_depth
	 [[node gradients/convolution_grad/Conv2DBackpropFilter (defined at /home/useradmin/SimpleHTR/src/Model.py:47) ]]

Errors may have originated from an input operation.
Input Source operations connected to node gradients/convolution_grad/Conv2DBackpropFilter:
 ExpandDims_1 (defined at /home/useradmin/SimpleHTR/src/Model.py:94)

Original stack trace for 'gradients/convolution_grad/Conv2DBackpropFilter':
  File "main.py", line 158, in <module>
    main()
  File "main.py", line 145, in main
    model = Model(loader.charList, decoderType)
  File "/home/useradmin/SimpleHTR/src/Model.py", line 47, in __init__
    self.optimizer = tf.compat.v1.train.AdamOptimizer().minimize(self.loss)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 172, in gradients
    unconnected_gradients)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 684, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 340, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 684, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/nn_grad.py", line 606, in _Conv2DGrad
    data_format=data_format)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1132, in conv2d_backprop_filter
    name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'convolution', defined at:
  File "main.py", line 158, in <module>
    main()
[elided 0 identical lines from previous traceback]
  File "main.py", line 145, in main
    model = Model(loader.charList, decoderType)
  File "/home/useradmin/SimpleHTR/src/Model.py", line 40, in __init__
    self.setupRNN()
  File "/home/useradmin/SimpleHTR/src/Model.py", line 98, in setupRNN
    self.rnnOut3d = tf.squeeze(tf.nn.atrous_conv2d(value=concat, filters=kernel, rate=1, padding='SAME'), axis=[2])
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1752, in atrous_conv2d
    name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1000, in convolution
    name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1150, in convolution_internal
    name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2604, in _conv2d_expanded_batch
    name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 973, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/useradmin/SimpleHTR/src/env1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)

**Comment by githubharald** [comment]
Maybe because your dataset has a different set of characters?
Can you add a `print(self.charList)` after this line and post the output of this print: 
https://github.com/githubharald/SimpleHTR/blob/master/src/DataLoaderIAM.py#L85

**Comment by Sofiane23i** [comment]
yes i use a different set of characters (French characters)

**Comment by premtibadiya** [comment]
@Sofiane23i  did you solve the error because I am using english characters and even then getting the same error

**Comment by Sofiane23i** [comment]
> @Sofiane23i did you solve the error because I am using english characters and even then getting the same error
> @githubharald please tell me what the error states because I am trying transfer learning on IAM dataset and using my own dataset.

Hello,

I suppose that you prepare your data to IAM format, then when you run the main file in training mode  with specific decoder  based on old weights of IAM dataset you will got an error. Like the author said your dataset has a different set of characters that IAM characters

here the characters list of IAM dataset !"#&'()*+,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz 

when you run the main file, after obtaining the error check the charList.txt file situated in model folder and compare it to the previous list, you need to fix this error by adding new words to your data that complete the remaining characters.
