### ISSUE TITLE
facing some issue while runing your code

### ISSUE THREAD

**Issue by harjai16** [githubharald/SimpleHTR#139]
bro i m facing some error while running your project handwritten  text 

facing 3 errors 
Traceback (most recent call last):
  File "C:/Users/ashwa/Downloads/SimpleHTR-master/src/main.py", line 201, in <module>
    main()
  File "C:/Users/ashwa/Downloads/SimpleHTR-master/src/main.py", line 196, in main
    model = Model(char_list_from_file(), decoder_type, must_restore=True, dump=args.dump)
  File "C:/Users/ashwa/Downloads/SimpleHTR-master/src/main.py", line 41, in char_list_from_file
    with open(FilePaths.fn_char_list) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../model/charList.txt'
 could you please help me

**Comment by githubharald** [comment]
follow instructions in README
