### ISSUE TITLE
pip install error: ModuleNotFoundError: No module named 'patch_ng'

### ISSUE THREAD

**Issue by huanghaiyang** [githubharald/SimpleHTR#160]
`
pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting editdistance==0.5.2 (from -r ./requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/07/61/9fac12e2688bc59d8b6a575e952826d93120e44d8db1bb7fe6c60e6994a1/editdistance-0.5.2.tar.gz (20 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting lmdb==1.0.0 (from -r ./requirements.txt (line 2))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/18/48109367e0d1bc9f7eed0d387cd5b50dd0e19c299bbbfe8b21246455fa48/lmdb-1.0.0.tar.gz (876 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [24 lines of output]
  py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
  Traceback (most recent call last):
    File "<string>", line 92, in <module>
  ModuleNotFoundError: No module named 'patch_ng'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "c:\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\huanh\AppData\Local\Temp\pip-build-env-4c2ncyro\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\huanh\AppData\Local\Temp\pip-build-env-4c2ncyro\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\huanh\AppData\Local\Temp\pip-build-env-4c2ncyro\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\huanh\AppData\Local\Temp\pip-build-env-4c2ncyro\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 94, in <module>
  Exception: Building py-lmdb from source on Windows requires the "patch-ng" python module.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

`

**Comment by mk3-14159** [comment]
How did you solve this?
