### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Vrindabv** [githubharald/SimpleHTR#23]
I'm getting two errors while I tried to run main.py . Below I have shared the error that I have got

**Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 133, in main
    print(open(FilePaths.fnAccuracy).read())
IOError: [Errno 2] No such file or directory: 'Documents/GitHub/SimpleHTR/model/accuracy.txt'**

PS: I have given the Path correctly only but somehow its shows error message. and I don't know why it shows a Traceback error for main.py.
Please help me to resolve it. I'm completely new to this and on a learning stage.

**Comment by githubharald** [comment]
please fill out the issue template.

**Comment by githubharald** [comment]
Closing because of inactivity.
