### ISSUE TITLE
Training model on IAM Dataset

### ISSUE THREAD

**Issue by juzer-lamo53** [githubharald/SimpleHTR#4]
Hi,

According to your guide for training model on IAM Dataset, when I run "python main.py --train".
I receive the following error:
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    infer(fnInfer)
  File "main.py", line 86, in infer
    model = Model(open(fnCharList).read(), mustRestore=True)
  File "E:\Users\Juzer\Dropbox\Master Thesis - Automatic Handling of Sheets\Implementation\SimpleHTR-master\SimpleHTR-master\src\Model.py", line 33, in __init__
    (self.sess, self.saver) = self.setupTF()
  File "E:\Users\Juzer\Dropbox\Master Thesis - Automatic Handling of Sheets\Implementation\SimpleHTR-master\SimpleHTR-master\src\Model.py", line 106, in setupTF
    raise Exception('No saved model found in: ' + modelDir)
Exception: No saved model found in: ../model/

Can you help me?

Thanks in advance.

**Comment by juzer-lamo53** [comment]
Yes, I did download the IAM Dataset for words and included it according to the instructions but I receive the mentioned error.

**Comment by juzer-lamo53** [comment]
Hi, can you help me about what can be the issue?

**Comment by githubharald** [comment]
I come back to you by the end of this week.

**Comment by githubharald** [comment]
you have an old version of the repository but used the recent version of the README. The command line arguments changed since then.
The solution should be pretty simple: just get the newest version of this repository and you're done ;-)
