### ISSUE TITLE
ModuleNotFoundError: No module named 'editdistance.bycython'

### ISSUE THREAD

**Issue by nikunjsi** [githubharald/SimpleHTR#50]
I am having an issue when running a text recognition program. 

In [6]: runfile('D:/MachineLearning/Github/SimpleHTR-master/src/main.py', wdir='D:/MachineLearning/Github/SimpleHTR-master/src')
Traceback (most recent call last):

  File "<ipython-input-6-75a8a603ecaf>", line 1, in <module>
    runfile('D:/MachineLearning/Github/SimpleHTR-master/src/main.py', wdir='D:/MachineLearning/Github/SimpleHTR-master/src')

  File "C:\Users\nikun\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\nikun\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/MachineLearning/Github/SimpleHTR-master/src/main.py", line 7, in <module>
    import editdistance

  File "C:\Users\nikun\Anaconda3\lib\site-packages\editdistance\__init__.py", line 1, in <module>
    from .bycython import eval

ModuleNotFoundError: No module named 'editdistance.bycython'

This is the error I am facing
I have looked for editdistance.bycython but I couldn't find any module like this.
I have pip installed cython module but it was of no use

Please hel

**Comment by githubharald** [comment]
closing because this is not an issue of this repo.
