### ISSUE TITLE
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,512,50] rhs shape= [1,1,512,80]

### ISSUE THREAD

**Issue by Michael-Stanz** [githubharald/SimpleHTR#72]
I  changed the dataloader.py to re-train the model(snapshot-38) with new dataset, however, when I try to retrain the model from the saved screenshots, I encounter the following error:

```
Init with stored values from ../model/snapshot-38
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,50] rhs shape= [1,1,512,80]
         [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, s
ave/RestoreV2_15)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 145, in <module>
    main()
  File "main.py", line 131, in main
    model = Model(loader.charList, decoderType)
  File "C:\Users\HP\Desktop\Handwritten-Text-Recognition\src\Model.py", line 51, in __init__
    (self.sess, self.saver) = self.setupTF()
  File "C:\Users\HP\Desktop\Handwritten-Text-Recognition\src\Model.py", line 150, in setupTF
    saver.restore(sess, latestSnapshot)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,50] rhs shape= [1,1,512,80]
         [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, s
ave/RestoreV2_15)]]

Caused by op 'save/Assign_15', defined at:
  File "main.py", line 145, in <module>
    main()
  File "main.py", line 131, in main
    model = Model(loader.charList, decoderType)
  File "C:\Users\HP\Desktop\Handwritten-Text-Recognition\src\Model.py", line 51, in __init__
    (self.sess, self.saver) = self.setupTF()
  File "C:\Users\HP\Desktop\Handwritten-Text-Recognition\src\Model.py", line 139, in setupTF
    saver = tf.train.Saver(max_to_keep=1) # saver saves model to file
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1140, in __init__
    self.build()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 688, in build
    restore_sequentially, reshape)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,512,50] rhs shape= [1,1,512,80]
         [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, s
ave/RestoreV2_15)]]

```
However, no variables were changed in the model.py. Except the 
`self.numTrainSamplesPerEpoch = 2000` in the Dataloader.py.

When I train from scratch, after deleting the snapshot-38 I am able to train the model for the new dataset. But when this newly trained model is used to be trained on iam dataset the above error again pops up.

So, can u please tell me where I went wrong?

**Comment by githubharald** [comment]
seems to be caused by the different number of characters in the datasets (50 vs 80).
The option to continue training was meant to continue training with the same dataset (imagine the situation in which you have new characters in the new dataset, but the model was created with as many character outputs as needed for the old dataset).
So the easiest way to handle this would be to train the model from scratch.

**Comment by Michael-Stanz** [comment]
Thanks for reply, I realized the mistake
